import React from 'react';
import Data from "../Assets/images/data.png"

const About = () => {
  return (
    <div className='flex flex-col lg:flex-row  gap-20 justify-between mx-10 mt-20 '>

<img src={Data}/>
<div>
  <h1 className='text-7xl text-center font-semibold text-white'>
Why Log-Eye??
  </h1>
  <div className='grid s:grid-cols-1 lg:grid-cols-2 mt-10 gap-10' >
<article className='flex flex-col gap-2'>
<h1 className='text-2xl text-white'>The Log-Eye Project acts as a vigilant guardian for your web server environment.</h1>
<p className='text-gray-300'>&#8594; Log-Eye stands as a vigilant guardian, tirelessly monitoring every interaction within your web server environment. Through meticulous logging of both Windows and network activities.</p>
</article>


<article className='flex flex-col gap-2'> 
<h1 className='text-2xl text-white'>It keeps a watchful eye on every interaction within the server.</h1>
<p className='text-gray-300'>&#8594;Log-Eye maintains vigilant oversight, meticulously tracking and analyzing every interaction within the server environment.it ensures that no activity goes unnoticed, providing a robust defense against potential security threats.</p>
</article>

<article className='flex flex-col gap-2'>
<h1 className='text-2xl text-white'> Comprehensive logs generated by Log-Eye provide insights into potential security threats</h1>
<p className='text-gray-300'>&#8594;The comprehensive logs generated by Log-Eye offer valuable insights into potential security threats lurking within your server environment. Log-Eye empowers organizations to identify and address vulnerabilities before they escalate into significant breaches.</p>
</article>


<article className='flex flex-col gap-2'>
<h1 className='text-2xl text-white'>Utilizes advanced algorithms to analyze log data instantly.</h1>
<p className='text-gray-300'>&#8594;Log-Eye leverages cutting-edge algorithms to analyze log data in real-time, enabling swift detection of anomalies and suspicious patterns. This instantaneous analysis ensures timely responses to emerging threats, bolstering the security posture of your web server environment.</p>
</article>

  </div>
</div>

    </div>
  )
}

export default About
